"""Render edl.csv as edl.md (phone-readable shot table with programme timecodes)."""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))
from assemble import load_edl  # noqa: E402
MOTION = {"none": "as shot", "push": "push 1.00→1.04", "zoom_in": "zoom 1.00→1.15", "zoom_out": "zoom 1.15→1.00", "pan_lr": "pan L→R", "pan_rl": "pan R→L"}
PART = {"P1": "Part 1 · Hook: the absolute rule of cold (ICE)", "P2": "Part 2 · Tummo and the Harvard tests (EMBER)",
        "P3": "Part 3 · Wim Hof, brown fat and the verdict (STEEL)"}


def tc(t):
    return f"{int(t // 60):02d}:{t % 60:05.2f}"


rows, total = load_edl(keep_optional=True)
out = ["# Step 2: EDL (shot list)\n",
       "Generated from `edl.csv` (itself generated by `tools/gen_edl.py`); edit `gen_edl.py`, not this file. **Prog** = final video time. "
       "Every shot gets grain + vignette and the logo bug; `illus` = \"ILLUSTRATIVE FOOTAGE\" tag; `hf/…` = HyperFrames scene "
       "(`video/fireice/<scene>/`), labelled inside the scene. Credits print top-right on third-party footage.\n"]
part = None
for r in rows:
    p = r["line"].split()[0]
    if p != part:
        part = p
        out.append(f"\n## {PART[p]}\n\n| # | Prog | Dur | VO line | Asset (in) | Motion / layers | On-screen text | Credit | SFX · note |\n|---|---|---|---|---|---|---|---|---|")
    src = f"`{r['asset']}`" + (f" @{r['src_in']:.1f}s" if r["src_in"] else "")
    layers = MOTION[r["motion"]] + (" · illus" if "illus" in r["overlay"] else "") + (" · " + r["fx"] if r["fx"] else "")
    extra = " · ".join(x for x in (r["sfx"], r["note"]) if x)
    out.append(f"| {r['id']} | {tc(r['start'])} | {r['dur']:.2f} | {r['line']} | {src} | {layers} | {r['text']} | {r['credit']} | {extra} |")
out.append(f"\n**Programme: {tc(total)}** ({len(rows)} shots).\n")
out.append("""## Audio cue sheet
| Element | Level | Notes |
|---|---|---|
| Voiceover (`assets/voiceover.wav`, `tools/build_vo.py`) | lead | 3 ElevenLabs parts joined with 1.6 s and 1.2 s section pauses |
| Music bed (`assets/audio/bgm_bed.wav`, `tools/make_bed.py`) | −17 dB, side-chain ducked under the VO | swells in pauses and the section breaks |
| SFX | per row (`file@seconds-into-shot@dB`) | blizzard, ice cracks, fire, steam, singing bowl, whoosh on the logo |
| Master | two-pass linear loudness, −14 LUFS / −1 dBTP | `assemble.py build_audio` |
""")
(HERE / "edl.md").write_text("\n".join(out), encoding="utf-8")
print("wrote edl.md")
