// Build the breath-hold documentary as N standalone HyperFrames part projects.
// Scenes are authored in VOICEOVER time (scenes.data.mjs); live pauses from
// runs/breath-hold/master/pause_map.json shift them into VIDEO time. A scene with
// `hold: true` sits inside the pause that starts at its `start`.
// Usage: node video/breathhold/build.mjs
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { scenes, parts } from "./scenes.data.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../..");
const master = join(root, "runs/breath-hold/master");
const pmap = JSON.parse(readFileSync(join(master, "pause_map.json"), "utf8"));
const shift = (t, hold) => t + pmap.pauses.filter((p) => (hold ? p.at < t : p.at <= t)).reduce((a, p) => a + p.len, 0);
const r3 = (x) => Math.round(x * 1000) / 1000;

// Absolute video times; durations follow the next scene's start so there are no gaps.
const abs = scenes.map((s) => ({ ...s, vstart: r3(shift(s.start, s.hold)) }));
abs.forEach((s, i) => {
  const next = i + 1 < abs.length ? abs[i + 1].vstart : pmap.video_duration;
  s.vdur = r3(next - s.vstart);
});

const fontFace = [400, 600, 800].map((w) =>
  `@font-face { font-family: "Inter"; font-weight: ${w}; src: url("vendor/fonts/inter-latin-${w}-normal.woff2") format("woff2"); }\n` +
  `      @font-face { font-family: "Noto Sans Telugu"; font-weight: ${w}; src: url("vendor/fonts/noto-sans-telugu-telugu-${w}-normal.woff2") format("woff2"); }`).join("\n      ");

for (const [k, part] of parts.entries()) {
  const id = `p${k + 1}`;
  const first = abs.findIndex((s) => s.id === part.from);
  const last = k + 1 < parts.length ? abs.findIndex((s) => s.id === parts[k + 1].from) : abs.length;
  const ss = abs.slice(first, last);
  const t0 = ss[0].vstart;
  const t1 = last < abs.length ? abs[last].vstart : pmap.video_duration;
  const dur = r3(t1 - t0);
  const dir = join(here, id);
  mkdirSync(dir, { recursive: true });
  cpSync(join(here, "_shared"), join(dir, "shared"), { recursive: true });
  execFileSync("ffmpeg", ["-y", "-loglevel", "error", "-ss", String(t0), "-t", String(dur), "-i", join(master, "voice_paused.wav"),
    "-ar", "48000", "-ac", "1", join(dir, "voice.wav")]);
  const local = ss.map(({ vstart, vdur, ...s }) => ({ ...s, start: r3(vstart - t0), dur: vdur }));
  writeFileSync(join(dir, "index.html"), `<!doctype html>
<html lang="te">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>16-minute breath hold: ${id}</title>
    <script src="vendor/gsap.min.js"></script>
    <link rel="stylesheet" href="shared/theme.css" />
    <script src="shared/scenes.js"></script>
    <style>
      ${fontFace}
    </style>
  </head>
  <body>
    <!-- Generated by video/breathhold/build.mjs from scenes.data.mjs. Edit those, not this file. -->
    <div id="root" data-composition-id="${id}" data-start="0" data-width="1920" data-height="1080" data-duration="${dur}">
      <div class="bg"></div>
      <div class="bg-vignette"></div>
      <div id="stage"></div>
      <audio id="${id}-voice" src="voice.wav" data-start="0" data-duration="${dur}" data-track-index="10" data-volume="1"></audio>
    </div>
    <script>
      const tl = gsap.timeline({ paused: true });
      HF_build(tl, ${JSON.stringify(local, null, 1)}, ${JSON.stringify(part.opts || {})});
      window.__timelines["${id}"] = tl;
    </script>
  </body>
</html>
`);
  console.log(`${id}: ${t0.toFixed(2)}-${t1.toFixed(2)} (${dur.toFixed(2)}s, ${ss.length} scenes)`);
}
writeFileSync(join(master, "scene_times.json"), JSON.stringify(abs.map(({ id, type, vstart, vdur }) => ({ id, type, start: vstart, dur: vdur })), null, 1) + "\n");
