// Scene list for the 16-minute breath-hold documentary.
// `start` is VOICEOVER time in seconds (see runs/breath-hold/transcript/); build.mjs shifts
// it past the live pauses. Offsets inside a scene (`at`, `keys`, `log[].at`) are relative
// to the scene start. Every on-screen fact traces to runs/breath-hold/research/facts.md.
const L = (s) => s; // marker for Telugu text (i18n-ready: all strings live here)

export const scenes = [
  // ───────────── BLOCK 1: the impossible question + the stage event
  { id: "hook", type: "question", start: 0.0, title: L("సాధారణ మనిషి ఎంతసేపు ఊపిరి ఆపగలడు?"), sub: L("30 సెకన్లు? 1 నిమిషం?") },
  { id: "limits", type: "ladder", start: 6.3, title: L("ఊపిరి ఆపితే, నిమిషం నిమిషానికి"),
    at: [0.3, 2.9, 6.3, 11.8], rowH: 132,
    items: [
      { t: "~2:00", te: L("చాలా మందికి ఇదే పరిమితి"), color: "o2" },
      { t: "2:00+", te: L("ఊపిరితిత్తులు మండటం మొదలు"), color: "gold" },
      { t: "3:00+", te: L("మెదడు కణాలకు ఆక్సిజన్ అందదు"), color: "co2" },
      { t: "6:00+", te: L("Brain damage ప్రమాదం"), color: "alarm" },
    ], src: "General guidance for untrained people; limits vary by person" },
  { id: "claim", type: "timer", start: 23.0, from: 0, to: 960, runAt: 0.5, runDur: 10.5, ease: "power2.in",
    eyebrow: "Mumbai · October 2026", title: L("16 నిమిషాలు"), sub: L("ఒక్క శ్వాస లేకుండా, కనురెప్ప వేయకుండా, కెమెరాల ముందు"),
    tag: "As reported by Indian media", tagClass: "gold",
    src: "Some outlets reported about 15 minutes. Do not try this: breath-holding without training can cause blackout." },
  { id: "signs", type: "bullets", start: 35.3, title: L("స్టేజ్ మీద కనిపించింది"), at: [0.3, 3.0, 5.2], color: "gold",
    items: [L("కళ్ళలోంచి కన్నీళ్ళు"), L("శరీరంలో సన్నని వణుకు"), L("ముఖంలో భయం లేదు, చూపు కదలలేదు")] },
  { id: "trick", type: "compare", start: 42.4, title: L("ఇది నిజమేనా?"), at: [1.6, 4.4],
    a: { eyebrow: "Theory 1", title: L("Magic trick?"), big: "?", color: "co2", sub: "" },
    b: { eyebrow: "Theory 2", title: L("Camera editing?"), big: "?", color: "calm", sub: "" } },
  { id: "live", type: "title", start: 48.9, eyebrow: "Not a trick", title: L("Live మీడియా కెమెరాల ముందు"),
    sub: L("వందలాది మంది చూస్తుండగా జరిగింది"), tag: "Live event", tagClass: "o2" },
  { id: "who", type: "title", start: 56.2, eyebrow: "Mumbai · Street Fighter promotion event", title: L("విద్యుత్ జమ్వాల్"),
    sub: L("Indian martial arts star · Hollywood debut"), tag: "Street Fighter (2026)", tagClass: "gold" },
  { id: "dhalsim", type: "term", start: 66.5, eyebrow: "His character", te: "Dhalsim", en: L("ధల్సిమ్"), color: "calm", size: 170,
    def: L("Street Fighter లోని legendary Indian yogic warrior") },
  { id: "silent", type: "title", start: 73.6, center: true, eyebrow: "On stage", title: L("మైక్ లేదు. స్పీచ్ లేదు."),
    sub: L("ఒకే చోట, statue లా నిలబడిపోయారు") },
  { id: "vigil", type: "vigil", start: 80.2, eyebrow: "The hold, as narrated", respLabel: "Visible breathing", respVal: L("లేదు"),
    keys: [[0, 0], [0.4, 120], [6.3, 300], [13.8, 480], [14.9, 600], [16.2, 720], [30.1, 840], [38.7, 960], [46.6, 960]],
    log: [
      { at: 0.4, t: "02:00", te: L("Performance కి ready అవుతున్నారనుకున్నారు") },
      { at: 6.3, t: "05:00", te: L("ఛాతీ, పొట్ట: ఏ కదలికా లేదు") },
      { at: 13.8, t: "08:00", te: L("శ్వాస అసలు కనిపించట్లేదు") },
      { at: 17.6, t: "12:00", te: L("కళ్ళు తెరిచే ఉన్నాయి, ఒక్క blink లేదు"), color: "gold" },
      { at: 21.6, t: "12:00+", te: L("కళ్ళలోంచి ఆగని కన్నీళ్ళు"), color: "gold" },
      { at: 30.1, t: "14:00", te: L("కాళ్ళలో, శరీరంలో heavy వణుకు"), color: "alarm" },
      { at: 38.7, t: "16:00", te: L("ఆ స్థితి నుంచి బయటకు వచ్చారు"), color: "o2" },
      { at: 43.6, t: "16:00", te: L("శంఖం ఊదారు"), color: "gold" },
    ], window: 5, shiverAt: 30.1, shiverEnd: 38.6 },
  { id: "hold1", type: "hold", start: 127.0, hold: true, clock: "16:00", label: L("శంఖనాదం") },
  { id: "silence", type: "title", start: 127.0, center: true, eyebrow: "Mumbai", title: "The entire hall went pin-drop silent.", size: 84 },
  { id: "possible", type: "question", start: 130.1, title: L("16 నిమిషాల breath hold: మనిషికి సాధ్యమేనా?"), sub: L("అసలు అక్కడ ఏం జరిగింది?") },

  // ───────────── BLOCK 2: the science (CO2 vs O2)
  { id: "ch2", type: "title", start: 135.75, eyebrow: "Part 2 · The science", title: L("శ్వాస ఆపితే శరీరంలో ఏం జరుగుతుంది?"), size: 92 },
  { id: "myth", type: "compare", start: 140.7, at: [0.3, 6.0], title: L("ఊపిరి తీసుకోవాలనిపించేది ఎందుకు?"),
    a: { eyebrow: "Common belief", title: L("Oxygen అయిపోవడం వల్ల"), big: "O₂ ↓", color: "calm", sub: L("చాలామంది ఇలాగే అనుకుంటారు") },
    b: { eyebrow: "The science", title: L("CO₂ పెరగడం వల్ల"), big: "CO₂ ↑", color: "co2", sub: L("అసలు trigger ఇదే") } },
  { id: "co2", type: "lungs", start: 149.2, eyebrow: "Carbon dioxide", title: L("CO₂ రక్తంలోనే ఉండిపోతుంది"),
    co2From: 40, co2To: 60, phTo: 7.3, spasmAt: 2.0, sub: L("రక్తం ఆమ్లంగా (acidic) మారుతుంది") },
  { id: "chemo", type: "chemo", start: 158.1, eyebrow: "Chemoreceptors", title: L("మెదడులో అలారం మోగుతుంది"),
    sub: L("Diaphragm కి emergency signals: ఇదే hypercapnic response"), alarm: L("వెంటనే శ్వాస తీసుకో!") },
  { id: "spasm", type: "lungs", start: 171.1, eyebrow: "Involuntary spasms", title: L("Diaphragm అదుపు లేకుండా కొట్టుకుంటుంది"),
    co2From: 60, co2To: 75, phTo: 7.2, spasmAt: 0.15, sub: L("చివరి నిమిషాల్లో వణుకుకు ఇదే కారణం (narration)") },
  { id: "co2peak", type: "stat", start: 179.9, eyebrow: "Hypercapnia", big: "CO₂ ↑↑", color: "co2", size: 240,
    label: L("రక్తంలో CO₂ చాలా ఎక్కువ స్థాయికి"), sub: L("వణుకు దానికి సంకేతం అని narration చెబుతోంది") },
  { id: "records", type: "records", start: 186.3, title: L("Official world records: static apnea"), at: [3.7, 11.5],
    rows: [
      { name: "Stéphane Mifsud", sub: L("సాధారణ గాలి · నీటిలో · 2009"), secs: 695, color: "o2" },
      { name: "Budimir Šobat", sub: L("ముందు pure oxygen పీల్చి · 2021"), secs: 1477, color: "calm", tag: "O₂-assisted" },
    ], note: L("O₂-assisted records: challenge కి ముందు ~30 నిమిషాల వరకు pure oxygen పీల్చుతారు"), noteAt: 15.4,
    src: "Sources: AIDA (Mifsud, 2009), Guinness World Records (Šobat, 2021)" },
  { id: "nooxy", type: "bullets", start: 207.0, eyebrow: "Mumbai stage", title: L("కానీ విద్యుత్:"), at: [0.3, 4.1, 6.3], color: "gold",
    items: [L("✕  pure oxygen తీసుకోలేదు"), L("✕  నీటిలో తేలలేదు"), L("✓  Live స్టేజ్ మీద, నిలబడి")] },

  // ───────────── BLOCK 3: the yogic secrets
  { id: "how", type: "question", start: 215.5, title: L("మరి 16 నిమిషాలు ఎలా?"), sub: L("సమాధానం విద్యుత్ స్వయంగా చెప్పారు") },
  { id: "patanjali", type: "bullets", start: 222.1, eyebrow: "Patanjali Yoga Sutras", title: L("పతంజలి యోగ సూత్రాల నుంచి 2 techniques"),
    at: [5.2, 6.0], color: "gold", items: [L("1  త్రాటక (Trataka)"), L("2  కేవల కుంభక (Kevala Kumbhaka)")],
    src: "Vidyut Jammwal credited the Patanjali Yoga Sutras at the event (media reports)" },
  { id: "trataka", type: "term", start: 230.0, eyebrow: "Technique 1", te: L("త్రాటక"), en: "Trataka", color: "gold",
    def: L("Blink చేయకుండా ఒకే బిందువుపై దృష్టి నిలపడం") },
  { id: "waves", type: "waves", start: 237.2, title: L("కన్నీళ్ళు వచ్చేదాకా సాధన → మనసు ప్రశాంతం"), at: [0.3, 1.4, 2.5], settleAt: 7.6 },
  { id: "kevala", type: "term", start: 247.6, eyebrow: "Technique 2 · the most powerful secret", te: L("కేవల కుంభక"), en: "Kevala Kumbhaka", color: "calm" },
  { id: "kvsp", type: "compare", start: 250.8, at: [0.3, 6.9],
    a: { eyebrow: "Normal pranayama", title: L("పీల్చి hold, లేదా వదిలి hold"), sub: L("శ్వాసను మనం ఆపుతాం"), color: "o2" },
    b: { eyebrow: "Kevala Kumbhaka", title: L("మనసు నిశ్చలమైతే, శ్వాస తనంతట తానే ఆగుతుంది"), sub: L("Yogic texts చెప్పే స్థితి"), color: "calm" } },
  { id: "heart", type: "heart", start: 265.0, eyebrow: "Hypometabolic state", title: L("గుండె వేగం తగ్గుతుంది, రక్తం మెదడు, గుండెకే"),
    bpmFrom: 72, bpmTo: 44, sub: L("Illustration: stage మీద ఎవరూ measure చేయలేదు") },
  { id: "o2need", type: "stat", start: 276.0, big: "40–50%", color: "o2", label: L("శరీరానికి oxygen అవసరం తగ్గుతుంది"),
    tag: "Claim in the narration, not measured", tagClass: "calm" },
  { id: "micro", type: "term", start: 280.9, eyebrow: "Possible explanation", te: "Micro-ventilation", en: L("మైక్రో వెంటిలేషన్"), color: "o2", size: 130,
    def: L("బయటికి కనిపించనంత సూక్ష్మంగా, ముక్కు ద్వారా గాలి మార్పిడి జరుగుతూ ఉండొచ్చు") },
  { id: "haridas", type: "history", start: 291.6, year: "1837", place: L("లాహోర్ · మహారాజా రంజిత్ సింగ్ ఆస్థానం"), title: L("సాధు హరిదాస్"),
    at: [5.6, 11.8], lines: [L("British వైద్యుల ముందు, సీలు వేసిన పెట్టెలో"), L("40 రోజులు భూగర్భ సమాధి, తర్వాత సజీవంగా")],
    cite: "Historical account: J. M. Honigberger, 'Thirty-five Years in the East' (1852); Sir Claude Wade" },
  { id: "power", type: "title", start: 307.1, center: true, title: L("మన సంప్రదాయ యోగకి అంత శక్తి ఉంది"), size: 88 },

  // ───────────── BLOCK 4: the 35-year foundation, the message, outro
  { id: "overnight", type: "question", start: 310.2, title: L("ఇది overnight లో సాధ్యమా?"), sub: L("Absolutely impossible!") },
  { id: "y35", type: "stat", start: 315.3, eyebrow: "Behind 16 minutes of stillness", big: "35", color: "gold", size: 320,
    label: L("ఏళ్ల కఠిన సాధన") },
  { id: "roots", type: "years", start: 320.9, title: L("పునాది"), at: [0.4, 2.6, 6.8], subAt: 9.0,
    marks: [{ k: "Army family", v: L("సైనిక కుటుంబంలో జన్మ") }, { k: "Age 3", v: L("Kerala ఆశ్రమంలో చేరిక") }, { k: "35 years", v: L("కలరిపయట్టు సాధన") }],
    sub: L("Kalaripayattu: ప్రపంచంలోని పురాతన martial arts లో ఒకటి") },
  { id: "kalari", type: "term", start: 332.9, eyebrow: "Not just stunts", te: L("కలరిపయట్టు"), en: "Kalaripayattu", color: "gold",
    def: L("Nerves, మర్మ points, శ్వాస నియంత్రణ: ఒక పూర్తి ప్రాచీన శాస్త్రం") },
  { id: "regimen", type: "bullets", start: 343.3, eyebrow: "His training, per the narration", title: L("విద్యుత్ దినచర్య"), at: [0.2, 2.6, 4.6, 8.1], color: "o2",
    items: [L("Pure vegetarian"), L("Gym weights కాదు: bodyweight calisthenics"), L("Animal flow + Yoga"), L("Ropes, dupes లేని real stunts")] },
  { id: "legends", type: "title", start: 355.4, eyebrow: "Recognition", title: L("Bruce Lee, Jackie Chan సరసన"),
    sub: L("World top martial artists lists లో విద్యుత్ పేరు"), src: "Widely reported, e.g. Looper's 2018 list of top martial artists" },
  { id: "dhalsim2", type: "term", start: 362.6, eyebrow: "Why this demonstration?", te: "Dhalsim", en: L("ఈ live demo ఆ character కోసమే"), color: "calm", size: 170 },
  { id: "message", type: "title", start: 369.8, center: true, eyebrow: "After 16 minutes of silence", title: L("నేటి generation కి ఒక message"), size: 92 },
  { id: "rush", type: "bullets", start: 376.1, title: L("ప్రపంచం మొత్తం పరిగెడుతోంది"), at: [4.5, 5.6, 6.6, 7.6], color: "co2",
    items: ["Mobile screens", "Notifications", "Targets", "Stress"] },
  { id: "quote", type: "quote", start: 386.5, hold: true, te: L("ఒక్కసారి ఆగండి."), en: "“Ek baar ruk jao.”  (Just stop, once.)", who: "Vidyut Jammwal · Mumbai event" },
  { id: "realpower", type: "compare", start: 386.5, at: [2.4, 4.2], title: L("Real power ఎక్కడుంది?"),
    a: { eyebrow: "Not here", title: L("పరిగెత్తడంలో కాదు"), big: "✕", color: "co2", sub: "" },
    b: { eyebrow: "But here", title: L("ఒక్క second ఆగి ఉండగలగడంలో"), big: "✓", color: "o2", sub: "" } },
  { id: "superpower", type: "quote", start: 394.1, te: L("బయట ఎంత గందరగోళం ఉన్నా, లోపల ప్రశాంతంగా ఉండటమే ultimate superpower"), size: 76 },
  { id: "mindgame", type: "title", start: 400.9, center: true, eyebrow: "Modern science limits × ancient yoga", title: L("Fitness + Mind game"), size: 120 },
  { id: "ask", type: "question", start: 408.8, title: L("మీకేం అనిపించింది?"), sub: L("Pure yogic power అంటారా? Comments లో చెప్పండి") },
  { id: "end", type: "endscreen", start: 417.5, title: L("నచ్చితే Like · Share · Subscribe"), btn: "SUBSCRIBE",
    sub: L("⚠ శిక్షణ లేకుండా breath hold ప్రయత్నించకండి") },
];

// Part boundaries (scene ids). Each part renders as its own project.
export const parts = [
  { from: "hook", opts: { chapter: { n: "01", name: "The impossible question" } } },
  { from: "vigil", opts: { chapter: { n: "01", name: "The impossible question" } } },
  { from: "ch2", opts: { chapter: { n: "02", name: "The science" } } },
  { from: "records", opts: { chapter: { n: "02", name: "The science" } } },
  { from: "how", opts: { chapter: { n: "03", name: "The yogic secrets" } } },
  { from: "heart", opts: { chapter: { n: "03", name: "The yogic secrets" } } },
  { from: "overnight", opts: { chapter: { n: "04", name: "The 35-year foundation" } } },
  { from: "message", opts: { chapter: { n: "04", name: "The 35-year foundation" } } },
];
