// Lip-synced dialogue test scene for the host duo (original characters).
// Inputs: video/assets/duo/duo.svg (scripts/make_duo.mjs) and video/duo-talk/lipsync.json
// (scripts/make_lipsync.py). Output: video/duo-talk/index.html (HyperFrames composition).
// Technique: cut-out puppets with swapped mouth shapes, a shot list of crops of one stage
// (two-shot / singles), blinks, a hand swap and small head moves on the speaker.
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("../", import.meta.url);
const svg = readFileSync(new URL("video/assets/duo/duo.svg", root), "utf8").replace('width="1000" height="940" ', "");
const sync = JSON.parse(readFileSync(new URL("video/duo-talk/lipsync.json", root), "utf8"));

// Stage geometry: the SVG (1000x940 units) is placed at (428, 40) and 1064 px wide (1 unit = 1.064 px).
const toPage = ([u, v]) => [428 + u * 1.064, 40 + v * 1.064];
const FACE = { girl: toPage([285, 370]), boy: toPage([720, 374]) };
// A shot puts a stage point at a frame point with a given zoom; "push" is the slow zoom at its end.
const frame = (focus, s, at) => ({ x: at[0] - s * focus[0], y: at[1] - s * focus[1], scale: s });
const SHOTS = {
  two: [frame([960, 540], 1, [960, 540]), frame([960, 520], 1.06, [960, 540])],
  girl: [frame(FACE.girl, 1.85, [990, 500]), frame(FACE.girl, 1.95, [990, 500])],
  boy: [frame(FACE.boy, 1.85, [930, 500]), frame(FACE.boy, 1.95, [930, 500])],
};
const other = { girl: "boy", boy: "girl" };

const r = (n) => Math.round(n * 1000) / 1000;
const js = [];
const lines = sync.lines;
lines.forEach((line, i) => {
  const cut = i === 0 ? 0 : r(line.start - 0.15);
  const end = i < lines.length - 1 ? r(lines[i + 1].start - 0.15) : sync.duration;
  const [a, b] = SHOTS[line.shot];
  js.push(`// line ${i + 1}: ${line.speaker} (${line.shot} shot)`);
  js.push(`tl.set("#cam", ${JSON.stringify(a)}, ${cut});`);
  js.push(`tl.to("#cam", { ...${JSON.stringify(b)}, duration: ${r(end - cut)}, ease: "none" }, ${cut});`);
  // Singles hide the other character, like a cut to a close-up.
  js.push(`tl.set("#girl", { opacity: ${line.shot === "boy" ? 0 : 1} }, ${cut});`);
  js.push(`tl.set("#boy", { opacity: ${line.shot === "girl" ? 0 : 1} }, ${cut});`);
  // Speaker: head bob while talking; listener: head turned slightly toward the speaker.
  const sp = line.speaker;
  const pivot = { girl: "285 500", boy: "720 500" };
  const lean = { girl: 3, boy: -3 };
  js.push(`tl.to("#${sp}-head", { rotation: ${-lean[sp]}, duration: 0.45, ease: "sine.inOut", yoyo: true, repeat: ${Math.max(1, Math.floor((line.end - line.start) / 0.45) - 1) | 1}, svgOrigin: "${pivot[sp]}" }, ${r(line.start)});`);
  js.push(`tl.to("#${other[sp]}-head", { rotation: ${lean[other[sp]]}, duration: 0.4, ease: "sine.out", svgOrigin: "${pivot[other[sp]]}" }, ${r(line.start)});`);
  js.push(`tl.to("#${sp}-head", { rotation: 0, duration: 0.3, ease: "sine.out", svgOrigin: "${pivot[sp]}" }, ${r(line.end)});`);
  // Mouth keys: show one shape at a time.
  for (const k of line.mouth) {
    js.push(`mouth("${sp}", "${k.shape}", ${k.t});`);
  }
  if (line.wave) {
    js.push(`tl.to("#girl-arm", { rotation: 10, duration: 0.22, ease: "sine.inOut", yoyo: true, repeat: 5, svgOrigin: "205 548" }, ${r(line.start)});`);
    // Hand swap: the waving arm is replaced by a resting arm once the greeting ends.
    js.push(`tl.set("#girl-arm", { opacity: 0 }, ${end});`);
    js.push(`tl.set("#girl-arm-rest", { opacity: 1 }, ${end});`);
  }
});

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Hosts: lip-sync test</title>
    <!-- Generated by scripts/make_duo_talk.mjs; edit the generator, not this file. -->
    <script src="vendor/gsap.min.js"></script>
    <style>
      :root { --wall: #f4ece0; --wall-low: #eadfcd; --floor: #d9c3a3; --floor-edge: #c7ad88; --sky: #bfe3f2; --frame: #8a5a3c; --leaf: #6fae6a; --pot: #c56b4a; }
      body { margin: 0; background: var(--wall); }
      #root { position: relative; width: 1920px; height: 1080px; overflow: hidden; background: var(--wall); }
      #cam { position: absolute; left: 0; top: 0; width: 1920px; height: 1080px; transform-origin: 0 0; }
      /* Simple original set: wall, floor, window and a plant (layers move with the camera). */
      #wall { position: absolute; left: -400px; top: -300px; width: 2720px; height: 1260px; background: linear-gradient(var(--wall) 0%, var(--wall-low) 100%); }
      #floor { position: absolute; left: -400px; top: 960px; width: 2720px; height: 500px; background: var(--floor); border-top: 10px solid var(--floor-edge); }
      #window { position: absolute; left: 110px; top: 150px; width: 300px; height: 380px; background: linear-gradient(var(--sky), #e8f6fb); border: 16px solid var(--frame); border-radius: 10px; }
      #window::before { content: ""; position: absolute; left: 50%; top: 0; bottom: 0; width: 12px; margin-left: -6px; background: var(--frame); }
      #window::after { content: ""; position: absolute; top: 50%; left: 0; right: 0; height: 12px; margin-top: -6px; background: var(--frame); }
      #plant { position: absolute; left: 1580px; top: 640px; width: 220px; height: 330px; }
      #plant .pot { position: absolute; left: 50px; bottom: 0; width: 120px; height: 120px; background: var(--pot); border-radius: 0 0 26px 26px; }
      #plant .leaf { position: absolute; width: 90px; height: 150px; background: var(--leaf); border-radius: 50% 50% 50% 50% / 60% 60% 40% 40%; }
      #duo { position: absolute; left: 428px; top: 40px; width: 1064px; height: 1000px; }
      #duo svg { width: 100%; height: 100%; overflow: visible; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="duo-talk" data-start="0" data-width="1920" data-height="1080" data-duration="${sync.duration}">
      <div id="cam">
        <div id="wall"></div>
        <div id="window"></div>
        <div id="floor"></div>
        <div id="plant">
          <div class="leaf" style="left: 20px; top: 40px; transform: rotate(-25deg)"></div>
          <div class="leaf" style="left: 110px; top: 30px; transform: rotate(25deg)"></div>
          <div class="leaf" style="left: 65px; top: 0px"></div>
          <div class="pot"></div>
        </div>
        <div id="duo">${svg}</div>
      </div>
      <audio id="duo-voice" src="voice.wav" data-start="0" data-duration="${sync.duration}" data-track-index="10" data-volume="1"></audio>
    </div>
    <script>
      const tl = gsap.timeline({ paused: true });
      const mouth = (who, shape, t) => {
        tl.set("#" + who + "-mouth .m", { opacity: 0 }, t);
        tl.set("#" + who + "-mouth .m[data-shape=" + shape + "]", { opacity: 1 }, t);
      };
      mouth("girl", "X", 0);
      mouth("boy", "X", 0);
      const blink = (who, t) => {
        tl.to("#" + who + "-eyes .blink", { scaleY: 0.1, transformOrigin: "50% 50%", duration: 0.07, ease: "power1.in" }, t);
        tl.to("#" + who + "-eyes .blink", { scaleY: 1, transformOrigin: "50% 50%", duration: 0.09, ease: "power1.out" }, t + 0.07);
      };
      for (const t of [1.8, 5.1, 8.4, 11.6]) blink("girl", t);
      for (const t of [2.6, 4.6, 7.9, 8.15, 12.9]) blink("boy", t);
      ${js.join("\n      ")}
      tl.set({}, {}, ${sync.duration});
      window.__timelines = window.__timelines || {};
      window.__timelines["duo-talk"] = tl;
    </script>
  </body>
</html>
`;
writeFileSync(new URL("video/duo-talk/index.html", root), html);
console.log(`wrote video/duo-talk/index.html (${sync.duration}s, ${lines.length} lines)`);
