#!/usr/bin/env python3
"""Search and download free stock B-roll and photos through the Pixabay API (Pexels too once its key exists).

Keys come from the environment only (cloud environment settings), never from the repo:
  PIXABAY_API_KEY   (tested 2026-10-08: API and cdn.pixabay.com downloads work from cloud sessions)
  PEXELS_API_KEY    (optional; Pexels paused new API keys in Oct 2026)

  python3 scripts/stock_fetch.py search pixabay video "yellow flowers" [--n 10] [--min-width 1920]
  python3 scripts/stock_fetch.py get pixabay video 22634 --out projects/<slug>/assets/broll

`search` prints id, size, duration, tags and page URL so you can contact-sheet candidates first; `get` downloads the
largest rendition and prints a media_manifest.csv row (licence: Pixabay Content License, commercial use allowed, no
attribution required; we credit anyway). AI-tagged results are hidden by default: Pixabay mixes AI media into search
results, and AI shots must never pass as real footage. Photos: the API gives at most 1280 px without Pixabay's full-access approval.
Pixabay asks API users to cache results and not hotlink: download once, keep the file in the project's assets/.
"""
import argparse
import csv
import json
import os
import subprocess
import sys
import urllib.parse
import urllib.request
from pathlib import Path

UA = "Creator-stock/1.0 (+https://github.com/mkmk749278/Creator)"


def get_json(url, headers=None):
    req = urllib.request.Request(url, headers={"User-Agent": UA, **(headers or {})})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def key(name):
    k = os.environ.get(name)
    if not k:
        sys.exit(f"{name} is not set: add it in the cloud environment settings (Network secrets or environment variable)")
    return k


def pixabay(kind, **params):
    base = "https://pixabay.com/api/videos/" if kind == "video" else "https://pixabay.com/api/"
    params = {"key": key("PIXABAY_API_KEY"), "safesearch": "true", **params}
    if kind == "photo":
        params["image_type"] = "photo"
    return get_json(base + "?" + urllib.parse.urlencode(params))["hits"]


def pexels(kind, path, **params):
    base = "https://api.pexels.com/videos/" if kind == "video" else "https://api.pexels.com/v1/"
    return get_json(base + path + "?" + urllib.parse.urlencode(params), {"Authorization": key("PEXELS_API_KEY")})


AI_TAGS = ("ai generated", "ai-generated", "generated by ai", "ai art", "midjourney", "stable diffusion")


def is_ai(hit):
    """Pixabay mixes AI-generated media into results; it must never pass as real footage (PLAYBOOK §12)."""
    return any(t in hit.get("tags", "").lower() for t in AI_TAGS)


def best_pixabay(hit, kind):
    if kind == "video":
        v = max((v for v in hit["videos"].values() if v.get("url")), key=lambda v: v["width"])
        return v["url"], v["width"], v["height"]
    return hit["largeImageURL"], hit["imageWidth"], hit["imageHeight"]


def cmd_search(a):
    if a.site == "pixabay":
        hits = pixabay(a.kind, q=a.query, per_page=max(3, min(a.n, 200)),
                       **({"min_width": a.min_width} if a.min_width else {}))
        dropped = [h for h in hits if is_ai(h)]
        if not a.allow_ai:
            hits = [h for h in hits if not is_ai(h)]
        for h in hits[: a.n]:
            _, w, hh = best_pixabay(h, a.kind)
            dur = f"{h['duration']:>4}s" if a.kind == "video" else "     "
            print(f"{h['id']:>9}  {w}x{hh}  {dur}  {'[AI] ' if is_ai(h) else ''}{h['tags'][:70]}  {h['pageURL']}")
        if dropped and not a.allow_ai:
            print(f"({len(dropped)} AI-generated result(s) hidden; --allow-ai shows them for labelled illustration only)")
    else:
        res = pexels(a.kind, "search", query=a.query, per_page=a.n)
        for h in res.get("videos" if a.kind == "video" else "photos", []):
            dur = f"{h.get('duration', 0):>4}s" if a.kind == "video" else "     "
            print(f"{h['id']:>9}  {h['width']}x{h['height']}  {dur}  {h['url']}")


def cmd_get(a):
    a.out.mkdir(parents=True, exist_ok=True)
    if a.site == "pixabay":
        hit = pixabay(a.kind, id=a.id)[0]
        if is_ai(hit) and not a.allow_ai:
            sys.exit(f"pixabay {a.id} is tagged AI-generated; use --allow-ai only for a labelled ILLUSTRATION")
        url, w, h = best_pixabay(hit, a.kind)
        page, author, licence = hit["pageURL"], hit["user"], "Pixabay Content License"
        licence_url = "https://pixabay.com/service/license-summary/"
    else:
        hit = pexels(a.kind, f"videos/{a.id}" if a.kind == "video" else f"photos/{a.id}")
        if a.kind == "video":
            f = max(hit["video_files"], key=lambda f: (f.get("width") or 0))
            url, w, h = f["link"], f["width"], f["height"]
            author = hit["user"]["name"]
        else:
            url, w, h, author = hit["src"]["original"], hit["width"], hit["height"], hit["photographer"]
        page, licence, licence_url = hit["url"], "Pexels License", "https://www.pexels.com/license/"
    ext = ".mp4" if a.kind == "video" else Path(urllib.parse.urlparse(url).path).suffix or ".jpg"
    dest = a.out / f"{a.site}_{a.id}{ext}"
    subprocess.run(["curl", "-fsSL", "--retry", "3", "-A", UA, "-o", str(dest), url], check=True)
    w_ = csv.writer(sys.stdout, lineterminator="\n")
    w_.writerow(["file", "kind", "what_it_shows", "source_page", "file_url", "author", "licence", "licence_url",
                 "attribution", "width", "height"])
    w_.writerow([dest.name, a.kind, "TODO: literally what it shows", page, url, author, licence, licence_url,
                 f"{a.site.title()} / {author}", w, h])
    print(f"saved {dest} ({dest.stat().st_size / 1e6:.1f} MB)", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("search")
    s.add_argument("site", choices=["pixabay", "pexels"])
    s.add_argument("kind", choices=["video", "photo"])
    s.add_argument("query")
    s.add_argument("--n", type=int, default=10)
    s.add_argument("--min-width", type=int, default=0)
    s.add_argument("--allow-ai", action="store_true")
    g = sub.add_parser("get")
    g.add_argument("site", choices=["pixabay", "pexels"])
    g.add_argument("kind", choices=["video", "photo"])
    g.add_argument("id")
    g.add_argument("--out", type=Path, required=True)
    g.add_argument("--allow-ai", action="store_true")
    a = ap.parse_args()
    {"search": cmd_search, "get": cmd_get}[a.cmd](a)


if __name__ == "__main__":
    main()
